// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCvTYzKChRY9kYyBmdQjzTM1X3g4xOMtU',
    appId: '1:54830976835:web:8792a79e86014eba4e69f6',
    messagingSenderId: '54830976835',
    projectId: 'groceryapp-58a88',
    authDomain: 'groceryapp-58a88.firebaseapp.com',
    storageBucket: 'groceryapp-58a88.appspot.com',
    measurementId: 'G-GGJHXLHLD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA34HWvDiYSeQtGxGey0HWQwmDzm5SrI0',
    appId: '1:54830976835:android:261101b4f13d80304e69f6',
    messagingSenderId: '54830976835',
    projectId: 'groceryapp-58a88',
    storageBucket: 'groceryapp-58a88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI5OmiLVa7Qn0FTtsFjZ0E0jNaVENSwEQ',
    appId: '1:54830976835:ios:732bd7efdb8cd72b4e69f6',
    messagingSenderId: '54830976835',
    projectId: 'groceryapp-58a88',
    storageBucket: 'groceryapp-58a88.appspot.com',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI5OmiLVa7Qn0FTtsFjZ0E0jNaVENSwEQ',
    appId: '1:54830976835:ios:bc4a09b1a7bb151d4e69f6',
    messagingSenderId: '54830976835',
    projectId: 'groceryapp-58a88',
    storageBucket: 'groceryapp-58a88.appspot.com',
    iosBundleId: 'com.example.groceryApp.RunnerTests',
  );
}
